version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: build-image.dockerfile
    container_name: @declapract{variable.databaseName}
    command: postgres -c 'max_connections=500'
    ports:
      - 7821:5432
    environment:
      POSTGRES_PASSWORD: a-secure-password # default user is `postgres`
      POSTGRES_DB: @declapract{variable.databaseName} # creates the database for us automatically
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d homeservicesdb']
      interval: 5s
      timeout: 5s
      retries: 5
